[package]
name = "pong"
version = "0.1.0"
authors = ["Omnath Mandal"]
edition = "2021"
description = "Ping Pong Game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
